### ISSUE TITLE
Info de user disponibilizada publicamente

### ISSUE THREAD

**Issue by vania-leite** [tantch/LBAW-ProjeKtion#1]
info publica segundo base de dados: username, nome, data de nascimento, genero, morada (??), email e profile pic

No template que tinhamos feito para o A2, tinhamos também: Estatísticas (nr projetos concluídos, nr projetos a decorrer, nr de posts) (implica criar novas queries) e redes sociais (implica modificar base de dados).

Vou por agora só implementar como está na base de dados e módulos, e depois isto fica para melhoramento.

**Comment by lycantropus** [comment]
isso está em high priority? tenho ideia que nao...
